Estatery/Web/Controllers/LandController.cs
using Business.Abstract;
using Dtos.Requests;
using Dtos.Responses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class LandController : Controller
    {
        private ILandService _landService;
        private ILocationService _locationService;
        private ISalesCategoryService _salesCategoryService;
        private ISalesTypeService _salesTypeService;
        public LandController(ILandService landService, ILocationService locationService, ISalesCategoryService salesCategoryService, ISalesTypeService salesTypeService)
        {
            _landService = landService;
            _locationService = locationService;
            _salesCategoryService = salesCategoryService;
            _salesTypeService = salesTypeService;
        }
        public async Task<IActionResult> LandPage()
        {
            var lands = await _landService.GetAllLands();
            return View(lands);
        }
        [Authorize]
        public async Task<IActionResult> Create()
        {
            List<SelectListItem> locationItems = await getLocationForDropDown();
            List<SelectListItem> salescategoryItems = await getsalesCategoryForDropDown();
            List<SelectListItem> salestypeItems = await getsalesTypeForDropDown();
            ViewBag.Locations = locationItems;
            ViewBag.salescategoryItems = salescategoryItems;
            ViewBag.salestypeItems = salestypeItems;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(LandRequest landRequest)
        {
            var landinfo = _locationService.GetLocationById(Convert.ToInt32(landRequest.Location.CityName));
            landRequest.Location.CityName = landinfo.Result.CityName;
            landRequest.Location.DistrictName = landinfo.Result.DistrictName;
            var land = await _landService.AddLand(landRequest);
            return View();
        }
        public async Task<IActionResult> Update(int id)
        {
            if (await _landService.IsExist(id))
            {
                LandResponse landResponse = await _landService.GetLandById(id);
                List<SelectListItem> locationItems = await getLocationForDropDown();
                List<SelectListItem> salescategoryItems = await getsalesCategoryForDropDown();
                List<SelectListItem> salestypeItems = await getsalesTypeForDropDown();
                ViewBag.Locations = locationItems;
                ViewBag.salescategoryItems = salescategoryItems;
                ViewBag.salestypeItems = salestypeItems;
                return View(landResponse);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Update(LandUpdateRequest landUpdateRequest)
        {
            if (ModelState.IsValid)
            {
                var landinfo = _landService.GetLandById(Convert.ToInt32(landUpdateRequest.Id));
                landUpdateRequest.Location.CityName = landinfo.Result.Location.CityName;
                landUpdateRequest.Location.DistrictName = landinfo.Result.Location.DistrictName;
                landUpdateRequest.Location.Id = landinfo.Result.Id;
                var result = await _landService.UpdateLand(landUpdateRequest);
                if (result.Success == true)
                {
                    return RedirectToAction(nameof(LandPage));
                }
                return BadRequest();
            }
            return View();
        }
        private async Task<List<SelectListItem>> getsalesTypeForDropDown()
        {
            var selectedItems = new List<SelectListItem>();
            var salesTypes = await _salesTypeService.GetAllSalesTypes();
            foreach (var salestype in salesTypes)
            {
                selectedItems.Add(
                   new SelectListItem
                   {
                       Text = salestype.Name,
                       Value = salestype.Name.ToString()
                   });
            }
            return selectedItems;
        }
        private async Task<List<SelectListItem>> getsalesCategoryForDropDown()
        {
            var selectedItems = new List<SelectListItem>();
            var salesCategories = await _salesCategoryService.GetAllSalesCategories();
            foreach (var salescategory in salesCategories)
            {
                selectedItems.Add(
                   new SelectListItem
                   {
                       Text = salescategory.Name,
                       Value = salescategory.Name.ToString()
                   });
            }
            return selectedItems;
        }
        private async Task<List<SelectListItem>> getLocationForDropDown()
        {
            var selectedItems = new List<SelectListItem>();
            var locations = await _locationService.GetAllLocations();
            foreach (var location in locations)
            {
                selectedItems.Add(
                new SelectListItem
                {
                    Text = location.CityName + "/" + location.DistrictName,
                    Value = location.Id.ToString()
                });
            }
            return selectedItems;
        }
    }
}

Estatery/Web/Controllers/UserController.cs
using Business.Abstract;
using Dtos.Requests;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class UserController : Controller
    {
        private IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        [HttpGet]
        public IActionResult LoginPage()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LoginPage(UserLoginRequest userLoginRequest)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.ValidateUser(userLoginRequest);
                if (user.Result.Data != null)
                {
                    List<Claim> claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name,user.Result.Data.FirstName+user.Result.Data.SecondName),
                        new Claim(ClaimTypes.Email,user.Result.Data.Email)
                    };
                    ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(claimsPrincipal);
                    if (Url.IsLocalUrl("/Home/HomePage"))
                    {
                        return RedirectToAction("HomePage", "Home");
                    }
                }
                ModelState.AddModelError("LoginPage", "Kullanıcı Adı veya Şifre Hatalıdır");
            }
            
            return View();
        }
        [HttpGet]
        public IActionResult SignupPage()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignupPage(UserSignupRequest userSignupRequest)
        {
            var result =await _userService.SignupUser(userSignupRequest);
            if (result!=null)
            {
                return Redirect("/User/LoginPage");
            }
            ModelState.AddModelError("SignupPage", "Bu E posta adı zaten kullanılmakta");
            return Redirect("User/SignupPage");
           
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/Home/HomePage");
        }
    }
}

Estatery/Web/Controllers/WorkPlaceController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class WorkPlaceController : Controller
    {
        private IWorkPlaceService _workPlaceService;
        private ILocationService _locationService;
        private ISalesCategoryService _salesCategoryService;
        private ISalesTypeService _salesTypeService;
        public WorkPlaceController(IWorkPlaceService workPlaceService,ILocationService locationService,ISalesCategoryService salesCategoryService,ISalesTypeService salesTypeService)
        {
            _workPlaceService = workPlaceService;
            _locationService = locationService;
            _salesCategoryService = salesCategoryService;
            _salesTypeService = salesTypeService;
        }
        public async Task<IActionResult> WorkPlacePage()
        {
            var workplaces = await _workPlaceService.GetAllWorkPlaces();
            return View(workplaces);
        }

    }
}

Estatery/Web/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/Main.css" rel="stylesheet" />
</head>
<body>
    <div>
        <nav id="top-nav">
            <div class="nav-logo">
                <i class="fas fa-map-pin" style="margin-right: 3px;"></i>
                REAL ESTATERY
            </div>
            <div class="nav-options">
                <ul>
                    <li><a asp-action="HomePage" asp-controller="Home">Ev ilanları</a></li>
                    <li><a asp-action="LandPage" asp-controller="Land">Arazi ilanları</a></li>
                    <li><a asp-action="WorkPlacePage" asp-controller="WorkPlace">İş Yeri ilanları</a></li>
                    <li><a asp-action="Create" asp-controller="Home">Ev ilanı oluştur</a></li>
                    <li><a asp-action="Create" asp-controller="Land">Arazi ilanı oluştur</a></li>
                    <li><a asp-action="Create" asp-controller="WorkPlace">İş yeri ilanı oluştur</a></li>
                    <li class="nav-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link" asp-action="Logout" asp-controller="User">@User.Identity.Name (Çıkış Yap)</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-action="LoginPage" asp-controller="User">Giriş Yap</a>
                        }
                    </li>
                </ul>
            </div>
        </nav>

        @RenderBody()
    </div>
</body>
</html>

Estatery/Web/Views/Shared/_WorkPlaceCard.cshtml
@model Entities.Concrete.WorkPlace
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="@Html.Raw(Model.WorkPlaceImageUrls.First().Name.ToString())" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title"></h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">İlan Sahibi @Model.Advertiser.ToUpper()</li>
        <li class="list-group-item">Lokasyon: @Model.Location.CityName / @Model.Location.DistrictName </li>
        <li class="list-group-item">Satış Kategorisi: @Model.SalesCategory.Name</li>
        <li class="list-group-item">Satış Tipi @Model.SalesType.Name</li>
        <li class="list-group-item">Toplam : @Model.Price m2 </li>
    </ul>
      @Html.ActionLink("Edit", "Update", new { id = Model.Id }) 
</div>

Estatery/Web/Views/Shared/_landCard.cshtml
@model Entities.Concrete.Land

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="@Html.Raw(Model.LandImageUrls.First().Name.ToString())" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title"></h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">İlan Sahibi: @Model.Advertiser</li>
        <li class="list-group-item">Lokasyon @Model.Location.CityName / @Model.Location.DistrictName </li>
        <li class="list-group-item">Toplam : @Model.SquareMeter m2</li>
        <li class="list-group-item">@Model.SalesCategory.Name </li>
        <li class="list-group-item"></li>
    </ul>
    @Html.ActionLink("Edit", "Update", new { id = Model.Id })
</div>

Estatery/Web/Views/Shared/_realEstateCard.cshtml
@model Entities.Concrete.House

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="@Html.Raw(Model.HouseImageUrls.First().Name.ToString())" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title"></h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">İlan Sahibi @Model.Advertiser.ToUpper()</li>
        <li class="list-group-item">Yapım Yılı : @Model.ConstructionYear</li>
        <li class="list-group-item">Lokasyonu @Model.Location.CityName / @Model.Location.DistrictName </li>
        <li class="list-group-item">Bina Toplam : @Model.SquareMeter m2</li>
        <li class="list-group-item">@Model.NumberOfRooms Oda <i class="fas fa-bed fa-style-on"></i>  @Model.NumberOfBath Banyolu <i class="fas fa-bath fa-bed-style-on"></i>  </li>
        <li class="list-group-item">Kategori:@Model.SalesCategory.Name </li>
        <li class="list-group-item">Tip:@Model.SalesType.Name </li>
    </ul>
      @Html.ActionLink("Edit", "Update", new { id = Model.Id }) 
</div>